"use client";

import * as XLSX from "xlsx";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Download, Printer, FileText } from "lucide-react";

export default function ActionButtons({ data }: { data: any[] }) {
  // ฟังก์ชันโหลด Excel
  const handleExportExcel = () => {
    const formattedData = data.map(item => ({
      "Item Name": item._id,
      "Category": item.categoryDetails?.name || "-",
      "Current Total Qty": item.totalQuantity,
      "Minimum Level": item.minStockLevel,
      "Suggested Restock": (item.minStockLevel * 2) - item.totalQuantity,
      "Unit": item.unit
    }));

    const worksheet = XLSX.utils.json_to_sheet(formattedData);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, worksheet, "Purchase List");
    XLSX.writeFile(workbook, `Purchase_List_${new Date().toISOString().split('T')[0]}.xlsx`);
  };

  // 📄 ฟังก์ชันสร้างใบสั่งซื้อ (PO PDF)
  const handleGeneratePDF = () => {
    const doc = new jsPDF();
    
    doc.setFontSize(20);
    doc.text("Purchase Order (PO) / Restock Request", 14, 20);
    doc.setFontSize(10);
    doc.text(`Date: ${new Date().toLocaleDateString('en-GB')}`, 14, 30);
    doc.text(`Generated by: StockFlow ERP System`, 14, 36);

    const tableData = data.map((item, index) => [
      index + 1,
      item._id,
      item.categoryDetails?.name || "-",
      `${item.totalQuantity} ${item.unit}`,
      `${(item.minStockLevel * 2) - item.totalQuantity} ${item.unit}`
    ]);

    autoTable(doc, {
      startY: 45,
      head: [['#', 'Item Name', 'Category', 'Current Stock', 'Order Qty']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [79, 70, 229] }
    });

    doc.save(`PO_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="flex flex-wrap items-center gap-2 sm:gap-3 mt-4 sm:mt-0">
      <button onClick={() => window.print()} className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-700 hover:bg-gray-50 text-gray-700 dark:text-gray-300 px-3 py-2 rounded-lg flex items-center gap-2 text-sm font-medium shadow-sm">
        <Printer className="w-4 h-4" /> Print
      </button>
      <button onClick={handleExportExcel} className="bg-emerald-600 hover:bg-emerald-700 text-white px-3 py-2 rounded-lg flex items-center gap-2 text-sm font-medium shadow-sm">
        <Download className="w-4 h-4" /> Excel
      </button>
      <button onClick={handleGeneratePDF} className="bg-indigo-600 hover:bg-indigo-700 text-white px-3 py-2 rounded-lg flex items-center gap-2 text-sm font-medium shadow-sm">
        <FileText className="w-4 h-4" /> Generate PO (PDF)
      </button>
    </div>
  );
}